### ISSUE TITLE
Items can be "stolen" from GUIs

### ISSUE THREAD

**Issue by SpectralVulpine** [xFyreWolfx/PatternAPI#1] opened 2017-09-19 01:24 UTC
When buttons are not marked as "deny-rearrangement", they can be taken from a GUI and kept in the inventory, at which point they can be used as normal items for crafting.

**Comment by xFyreWolfx** [comment] 2017-09-21 19:09
Resolved in v1.0.3; please re-open if the problem is noticed again, with steps to reproduce.

**Closed by xFyreWolfx** 2017-09-21 19:09 UTC
Labels: bug
